blog_app/blog/urls.py
import blog.views as blog_views
from django.urls import path

app_name = "blog"

urlpatterns = [
    path("", blog_views.PostListView.as_view(), name="post_list"),
    path("post/create", blog_views.PostCreateView.as_view(), name="post_create"),
    path("post/<str:slug>", blog_views.PostSingleView.as_view(), name="post_detail"),
    path("post/<str:slug>/edit", blog_views.PostUpdateView.as_view(), name="edit_post"),
    path("post/<str:slug>/delete", blog_views.delete_post, name="delete_post"),
    path("post/add-comment/<str:post_id>", blog_views.AddCommentView.as_view(), name="add_comment"),
    path("category/<str:slug>", blog_views.PostListByCategoryView.as_view(), name="category"),
    path("author/<str:slug>", blog_views.PostListByAuthorView.as_view(), name="author"),
]

blog_app/blog_app/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from blog_app import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("account/", include("users.urls"), name="blog"),
    path("", include("blog.urls"), name="blog"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += debug_toolbar_urls()

blog_app/users/urls.py
import users.views as user_views
from django.contrib.auth import views as auth_views
from django.urls import path

app_name = "account"

urlpatterns = [
    path("register/", user_views.register, name="register"),
    path("login/", user_views.UserLoginView.as_view(), name="login"),
    path("edit/", user_views.UserUpdateView.as_view(), name="edit"),
    path("", user_views.UserDetailView.as_view(), name="detail"),
    path("logout/", auth_views.logout_then_login, name="logout"),
]

blog_app/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    bio = models.TextField(max_length=500, blank=True)
    avatar = models.ImageField(upload_to="avatar/%Y/%m/%d", null=True, blank=True)

blog_app/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UsernameField
from users.models import User


class UserRegisterForm(UserCreationForm):
    username = UsernameField(widget=forms.TextInput(attrs={"placeholder": "Username"}), label="")
    email = forms.EmailField(widget=forms.EmailInput(attrs={"placeholder": "Email"}), label="")
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "Password"}), label="")
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "Repeat password"}), label="")

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Username"}), label="")
    password = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "Password"}), label="")

    class Meta:
        model = User
        fields = ("username", "password")


class UserUpdateForm(forms.ModelForm):
    avatar = forms.ImageField(widget=forms.FileInput(), required=False)
    email = forms.EmailField(widget=forms.EmailInput(attrs={"placeholder": "Email"}))
    username = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Username"}))
    bio = forms.CharField(widget=forms.Textarea(attrs={"placeholder": "Bio"}), required=False)

    class Meta:
        model = User
        fields = ["avatar", "email", "username", "bio"]

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if User.objects.filter(email=email).exclude(pk=self.instance.pk).exists():
            raise forms.ValidationError("This email is already in use.")
        return email

    def clean_username(self):
        username = self.cleaned_data.get("username")
        if User.objects.filter(username=username).exclude(pk=self.instance.pk).exists():
            raise forms.ValidationError("This username is already in use.")
        return username

blog_app/users/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views import generic
from users.forms import UserLoginForm, UserRegisterForm, UserUpdateForm
from users.models import User


class UserLoginView(LoginView):
    template_name = "users/login.html"
    authentication_form = UserLoginForm
    redirect_authenticated_user = True


class UserDetailView(LoginRequiredMixin, generic.DetailView):
    model = User
    template_name = "users/detail.html"
    context_object_name = "user"

    def get_object(self):
        return self.request.user


class UserUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = "users/edit.html"
    context_object_name = "user"

    def get_object(self):
        return self.request.user

    def get_success_url(self):
        return reverse_lazy("account:detail")

    def form_valid(self, form):
        if form.is_valid():
            form.save()
            return redirect(self.get_success_url())
        return self.form_invalid(form)


def register(request):
    if request.user.is_authenticated:
        return redirect("blog:post_list")
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, f"Account successfully created. Now you can login")
            return redirect("account:login")
    else:
        form = UserRegisterForm()
    return render(request, "users/register.html", {"form": form})

blog_app/users/templates/users/detail.html
{% extends 'base.html' %}

{% load static %}

{% block title %}My Profile{% endblock %}

{% block content %}
    <article class="profile-detail">
        <header class="entry-header">
            <h1 class="entry-title">My Profile</h1>
        </header>
        <div class="entry-content">
            <p>
                {% if user.avatar %}
                    <img src="{{ user.avatar.url }}" alt="Avatar" width="64" height="64">
                {% else %}
                    <img src="{% static 'img/default-avatar.png' %}" alt="Avatar"  width="64" height="64">
                {% endif %}
            </p>
            <p><strong>Email:</strong> {{ user.email }}</p>
            <p><strong>Username:</strong> {{ user.username }}</p>
            <p><strong>Bio:</strong> {{ user.bio }}</p>
            <a href="{% url 'account:edit' %}">
                <button class="btn-send btn-5 btn-5b ion-ios-paperplane"><span>Edit Profile</span></button>
            </a>
        </div>
    </article>
{% endblock %}

blog_app/users/templates/users/edit.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Edit Profile{% endblock %}

{% block content %}
    <article class="profile-edit">
        <header class="entry-header">
            <h1 class="entry-title">Edit Profile</h1>
        </header>
        <div class="entry-content clearfix">
            <form method="POST" action="{% url 'account:edit' %}" enctype="multipart/form-data"
                  class="standard-form">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn-send btn-5 btn-5b ion-ios-paperplane"><span>Update</span></button>
            </form>
        </div>
    </article>
{% endblock %}

blog_app/users/templates/users/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
    <main class="col-md-12">
        <h1 class="page-title">Login</h1>
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} text-center" style="margin-top: 20px; margin-bottom: 0;">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
        <article class="post">
            <div class="entry-content clearfix">
                <form method="POST" class="standard-form">
                    <div class="row">
                        <div class="col-md-6 col-md-offset-3">
                            {% csrf_token %}
                            {{ form }}
                            <div class="text-center">
                                <p>Don't have an account? <a href="{% url 'account:register' %}">Register here</a></p>
                                <button class="btn-send btn-5 btn-5b ion-ios-paperplane"><span>Sign in</span></button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </article>
    </main>
{% endblock %}

blog_app/users/templates/users/register.html
{% extends 'base.html' %}

{% block title %}Register{% endblock %}

{% block content %}
    <main class="col-md-12">
        <h1 class="page-title">Register</h1>
        <article class="post">
            <div class="entry-content clearfix">
                <form method="POST" class="standard-form">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 col-md-offset-3">
                            {{ form }}
                            <div class="text-center">
                                <p>Already have an account? <a href="{% url 'account:login' %}">Login</a></p>
                                <button class="btn-send btn-5 btn-5b ion-ios-paperplane"><span>Sign up</span></button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </article>
    </main>
{% endblock %}