blog_app/blog/urls.py
import blog.views as blog_views
from django.urls import path

app_name = "blog"

urlpatterns = [
    path("", blog_views.PostListView.as_view(), name="post_list"),
    path("post/create", blog_views.PostCreateView.as_view(), name="post_create"),
    path("post/<str:slug>", blog_views.PostSingleView.as_view(), name="post_detail"),
    path("post/<str:slug>/edit", blog_views.PostUpdateView.as_view(), name="edit_post"),
    path("post/<str:slug>/delete", blog_views.delete_post, name="delete_post"),
    path("post/add-comment/<str:post_id>", blog_views.AddCommentView.as_view(), name="add_comment"),
    path("category/<str:slug>", blog_views.PostListByCategoryView.as_view(), name="category"),
    path("author/<str:slug>", blog_views.PostListByAuthorView.as_view(), name="author"),
]

blog_app/blog_app/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from blog_app import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("account/", include("users.urls"), name="blog"),
    path("", include("blog.urls"), name="blog"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += debug_toolbar_urls()

blog_app/users/urls.py
import users.views as user_views
from django.contrib.auth import views as auth_views
from django.urls import path

app_name = "account"

urlpatterns = [
    path("register/", user_views.register, name="register"),
    path("login/", user_views.UserLoginView.as_view(), name="login"),
    path("edit/", user_views.UserUpdateView.as_view(), name="edit"),
    path("", user_views.UserDetailView.as_view(), name="detail"),
    path("logout/", auth_views.logout_then_login, name="logout"),
]

blog_app/templates/inc/_footer.html
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy; PythonLab 2024</p>
            </div>
        </div>
    </div>
</footer>

blog_app/templates/inc/_header.html
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'blog:post_list' %}"><b>Django</b> &amp; Lab</a></h1>
                </div>
            </div>
            <div class="col-md-8 col-sm-7 col-xs-4">
                {% include 'inc/_pc_menu.html' %}
                {% include 'inc/_search.html' %}
            </div>
        </div>
    </header>
</div>

blog_app/templates/inc/_mobile_menu.html
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <form id="logoutMob" action="{% url 'account:logout' %}" method="POST">
            {% csrf_token %}
            <ul>
                <li><a href="{% url 'blog:post_list' %}" data-hover="Home">Home</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'account:detail' %}" data-hover="Account">Account</a></li>
                    <li onclick="logoutMob.submit()">
                        <a data-hover="Logout" style="cursor: pointer;">Logout</a>
                    </li>
                {% else %}
                    <li><a href="{% url 'account:login' %}" data-hover="Login">Login</a></li>
                {% endif %}
            </ul>
        </form>

    </nav>
</div>

blog_app/templates/inc/_paginator.html
{% load paginator_tags %}

{% if page_obj.number > 1 or page_obj.has_next %}
    <div class="text-center">
        <div class="pagination">
            {% get_proper_elided_page_range paginator page_obj.number as page_range %}
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}{% if q %}&q={{ q }}{% endif %}">&laquo;</a>
            {% endif %}
            {% for page_number in page_range %}
                {% if page_number == page_obj.paginator.ELLIPSIS %}
                    <a>{{ page_number }}</a>
                {% else %}
                    <a href="?page={{ page_number }}{% if q %}&q={{ q }}{% endif %}" class="{% if page_number == page_obj.number %}active{% endif %}">
                        {{ page_number }}
                    </a>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}{% if q %}&q={{ q }}{% endif %}">&raquo;</a>
            {% endif %}
        </div>
    </div>
{% endif %}

blog_app/templates/inc/_pc_menu.html
<nav class="main-nav" role="navigation">
    <div class="navbar-header">
        <button type="button" id="trigger-overlay" class="navbar-toggle">
            <span class="ion-navicon"></span>
        </button>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <form id="logoutPC" action="{% url 'account:logout' %}" method="POST">
            {% csrf_token %}
            <ul class="nav navbar-nav navbar-right">
                <li class="cl-effect-11"><a href="{% url 'blog:post_list' %}" data-hover="Home">Home</a></li>
                {% if user.is_authenticated %}
                    <li class="cl-effect-11"><a href="{% url 'account:detail' %}" data-hover="Account">Account</a></li>
                    <li class="cl-effect-11" onclick="logoutPC.submit()">
                        <a data-hover="Logout" style="cursor: pointer;">Logout</a>
                    </li>
                {% else %}
                    <li class="cl-effect-11"><a href="{% url 'account:login' %}" data-hover="Login">Login</a></li>
                {% endif %}
            </ul>
        </form>

    </div>
</nav>

blog_app/templates/inc/_search.html
<div id="header-search-box">
    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
    <div id="search-form" class="search-form">
        <form role="search" method="GET" id="searchform" action="">
            <input type="search" name="q" placeholder="Search" required>
            <button type="submit"><span class="ion-ios-search-strong"></span></button>
        </form>
    </div>
</div>