blog_app/blog/urls.py
import blog.views as blog_views
from django.urls import path

app_name = "blog"

urlpatterns = [
    path("", blog_views.PostListView.as_view(), name="post_list"),
    path("post/create", blog_views.PostCreateView.as_view(), name="post_create"),
    path("post/<str:slug>", blog_views.PostSingleView.as_view(), name="post_detail"),
    path("post/<str:slug>/edit", blog_views.PostUpdateView.as_view(), name="edit_post"),
    path("post/<str:slug>/delete", blog_views.delete_post, name="delete_post"),
    path("post/add-comment/<str:post_id>", blog_views.AddCommentView.as_view(), name="add_comment"),
    path("category/<str:slug>", blog_views.PostListByCategoryView.as_view(), name="category"),
    path("author/<str:slug>", blog_views.PostListByAuthorView.as_view(), name="author"),
]

blog_app/blog_app/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from blog_app import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("account/", include("users.urls"), name="blog"),
    path("", include("blog.urls"), name="blog"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += debug_toolbar_urls()

blog_app/users/urls.py
import users.views as user_views
from django.contrib.auth import views as auth_views
from django.urls import path

app_name = "account"

urlpatterns = [
    path("register/", user_views.register, name="register"),
    path("login/", user_views.UserLoginView.as_view(), name="login"),
    path("edit/", user_views.UserUpdateView.as_view(), name="edit"),
    path("", user_views.UserDetailView.as_view(), name="detail"),
    path("logout/", auth_views.logout_then_login, name="logout"),
]

blog_app/blog/models.py
from autoslug import AutoSlugField
from django.db import models
from django.urls import reverse
from users.models import User


class Category(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, unique=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:category", kwargs={"slug": self.slug})

    class Meta:
        verbose_name_plural = "categories"
        ordering = ["title"]


class Post(models.Model):
    title = models.CharField(max_length=50)
    slug = AutoSlugField(populate_from="title", unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    content = models.TextField()
    image = models.ImageField(upload_to="post-img/%Y/%m/%d", null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.title} (by {self.author.username})"

    def get_absolute_url(self):
        return reverse("blog:post_detail", kwargs={"slug": self.slug})

    class Meta:
        ordering = ["-created_at"]


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    content = models.TextField(max_length=350)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content

    class Meta:
        ordering = ["-created_at"]

blog_app/blog/forms.py
from blog.models import Post
from django import forms


class CommentForm(forms.Form):
    comment = forms.CharField(
        widget=forms.Textarea(
            attrs={"rows": 6, "maxlength": 350, "class": "form-control", "placeholder": "Enter your comment"}
        ),
        max_length=350,
        label="",
    )


class PostForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Title"}))
    image = forms.ImageField(widget=forms.FileInput(), required=False)
    content = forms.CharField(widget=forms.Textarea(attrs={"placeholder": "Content"}))

    class Meta:
        model = Post
        fields = ["title", "image", "content", "category"]

blog_app/blog/views.py
from blog.forms import CommentForm, PostForm
from blog.models import Comment, Post
from django import views
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Count, Prefetch, Q
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views import generic


class PostListView(generic.ListView):
    paginate_by = 1
    template_name = "blog/home.html"
    context_object_name = "posts"

    def get_queryset(self):
        queryset = (
            Post.objects.all()
            .select_related("author", "category")
            .annotate(comment_count=Count("comments"))
            .order_by("-created_at")
        )
        if q := self.request.GET.get("q"):
            queryset = queryset.filter(Q(title__icontains=q) | Q(content__icontains=q))
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["q"] = self.request.GET.get("q", "")
        return context


class PostListByCategoryView(PostListView):
    def get_queryset(self):
        slug = self.kwargs["slug"]
        return super().get_queryset().filter(category__slug=slug)


class PostListByAuthorView(PostListView):
    def get_queryset(self):
        slug = self.kwargs["slug"]
        return super().get_queryset().filter(author__username=slug)


class PostSingleView(generic.DetailView):
    template_name = "blog/detail.html"
    context_object_name = "post"

    def get_queryset(self):
        slug = self.kwargs["slug"]
        return (
            Post.objects.filter(slug=slug)
            .select_related("author", "category")
            .prefetch_related(Prefetch("comments", queryset=Comment.objects.select_related("author")))
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["comment_form"] = CommentForm()
        return context


class AddCommentView(LoginRequiredMixin, views.View):
    def post(self, request, post_id):
        post = get_object_or_404(Post, pk=post_id)
        form = CommentForm(request.POST)
        if form.is_valid():
            content = form.cleaned_data["comment"]
            Comment.objects.create(post=post, author=request.user, content=content)
            messages.success(request, "Your comment has been successfully added ")
        else:
            messages.error(request, "You comment has not been added")
        return redirect(f"{reverse('blog:post_detail', kwargs={'slug': post.slug})}#comments")


class PostCreateView(LoginRequiredMixin, generic.CreateView):
    model = Post
    form_class = PostForm
    template_name = "blog/edit.html"
    context_object_name = "post"

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("blog:post_detail", kwargs={"slug": self.object.slug})


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    model = Post
    form_class = PostForm
    template_name = "blog/edit.html"
    context_object_name = "post"

    def get_queryset(self):
        slug = self.kwargs["slug"]
        return Post.objects.filter(slug=slug)

    def get_success_url(self):
        return reverse_lazy("blog:post_detail", kwargs={"slug": self.object.slug})

    def test_func(self):
        post = get_object_or_404(Post, slug=self.kwargs["slug"])
        return self.request.user == post.author

    def handle_no_permission(self):
        return redirect("blog:post_detail", slug=self.kwargs["slug"])


@login_required
def delete_post(request, slug):
    post = get_object_or_404(Post, slug=slug)
    if request.user == post.author and request.method == "POST":
        messages.success(request, "Post has been successfully deleted")
        post.delete()
    return redirect(reverse_lazy("blog:post_list"))

blog_app/blog/templates/blog/base.html
{% extends 'base.html' %}
{% load sidebar_tags %}

{% block content %}
<aside class="col-md-3">
    {% categories %}
    {% recent_posts %}
    <div style="margin-top: 40px;">
        <a href="{% url 'blog:post_create' %}">
            <button class="btn-send btn-5 btn-5b ion-ios-paperplane"><span>Create post</span></button>
        </a>
    </div>
</aside>
<main class="col-md-9">
    {% block post_content %}{% endblock %}
</main>
{% endblock %}

blog_app/blog/templates/blog/blog_posts.html
{% extends 'blog/base.html' %}

{% block title %}All posts{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-12">

            {% for post in posts %}
            <!-- Blog Post -->
            <h2 class="post-title"><a href="post.html">{{ post.title }}</a></h2>
            <p>{{ post.content }}</p>
            <p>
                <span class="glyphicon glyphicon-time"></span> {{ post.created_at }} |
                <span class="glyphicon glyphicon-user"></span> {{ post.author.username|title }}
            </p>
            <a class="btn btn-default" href="post.html">Read More</a>
            <hr>
            {% empty %}
            <h3>No Content</h3>
            {% endfor %}

            <!-- Paginator -->
            {% include 'blog/paginator.html' %}
        </div>
    </div>
</div>
{% endblock %}

blog_app/blog/templates/blog/detail.html
{% extends 'blog/base.html' %}

{% load static %}

{% block title %}{{ post.title }}{% endblock %}

{% block post_content %}
    <article class="post post-1">
        <header class="entry-header">
            <h1 class="entry-title">{{ post.title|title }}</h1>
            <div class="text-center">
                <img src="{% if post.image %}{{ post.image.url }}{% else %}{% static 'img/no-image.jpg' %}{% endif %}"
                     class="post-img" alt="{{ post.title|title }}">
            </div>
            <div class="entry-meta">
                <span class="post-category"><a href="{{ post.category.get_absolute_url }}">{{ post.category.title }}</a></span>
                <span class="post-date"><a><time class="entry-date">{{ post.created_at }}</time></a></span>
                <span class="post-author"><a
                        href="{% url 'blog:author' post.author.username %}">{{ post.author.username }}</a></span>
                <span class="comments-link"><a>{{ post.comments.all|length }} Comments</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            <p class="break-word">{{ post.content }}</p>
        </div>
        {% if user.is_authenticated and user == post.author %}
            <div class="post-actions" style="display: flex; gap: 10px;">
                <a href="{% url 'blog:edit_post' post.slug %}">
                    <button class="btn-send btn-5 btn-5b ion-ios-paperplane"><span>Edit</span></button>
                </a>
                <form method="POST" action="{% url 'blog:delete_post' post.slug %}" style="display: inline;">
                    {% csrf_token %}
                    <button type="submit" class="btn-send btn-5"><span>Delete</span></button>
                </form>
            </div>
        {% endif %}
    </article>

    <!-- Comment Form -->
    <div class="comment-form">
        {% if user.is_authenticated %}
            <h4>Add comment</h4>
            <form method="POST" action="{% url 'blog:add_comment' post.id %}">
                {% csrf_token %}
                <div class="form-group">
                    {{ comment_form }}
                </div>
                <button type="submit" class="btn-send btn-5 btn-5b ion-ios-paperplane"><span>Send</span></button>
            </form>
        {% else %}
            <h4>To leave a comment you should <a href="{% url 'account:login' %}">log in</a></h4>
        {% endif %}
    </div>


    <!-- Comments Section -->
    <div id="comments" class="comments-section">
        <h4>Comments</h4>
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} text-center"
                     style="margin-top: 20px; margin-bottom: 0;">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
        {% for comment in post.comments.all %}
            <div class="comment">
                <div class="comment-author-avatar">
                    <img src="{% if comment.author.avatar %}{{ comment.author.avatar.url }}{% else %}{% static 'img/default-avatar.png' %}{% endif %}"
                         alt="{{ comment.author.username }}" class="img-circle" width="43" height="43">
                </div>
                <div class="comment-body">
                    <div class="comment-author-name">{{ comment.author.username }}</div>
                    <div class="comment-date">{{ comment.created_at }}</div>
                    <div class="comment-content">
                        <p class="break-word">{{ comment.content }}</p>
                    </div>
                </div>
            </div>
            {% empty %}
            <p>No comments yet.</p>
        {% endfor %}
    </div>
{% endblock %}

blog_app/blog/templates/blog/edit.html
{% extends 'blog/base.html' %}

{% load static %}

{% block title %}{% if post %}Edit Post{% else %}Create New Post{% endif %}{% endblock %}

{% block post_content %}
<article class="post post-1">
    <header class="entry-header">
        <h1 class="entry-title">
            {% if post %}Edit Post{% else %}Create New Post{% endif %}
        </h1>
    </header>
    <div class="entry-content clearfix">
        <form method="POST"
              action="{% if post %}{% url 'blog:edit_post' post.slug %}{% else %}{% url 'blog:post_create' %}{% endif %}"
              enctype="multipart/form-data"
              class="standard-form">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn-send btn-5 btn-5b ion-ios-paperplane">
                <span>{% if post %}Update{% else %}Create{% endif %}</span>
            </button>
        </form>
    </div>
</article>
{% endblock %}

blog_app/blog/templates/blog/home.html
{% extends 'blog/base.html' %}

{% load static %}

{% block title %}All posts{% endblock %}

{% block post_content %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} text-center"
                 style="margin-top: 20px; margin-bottom: 0;">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    {% for post in posts %}
        <article class="post post-1">
            <header class="entry-header">
                <h1 class="entry-title">
                    <a href="{{ post.get_absolute_url }}">{{ post.title|title }}</a>
                </h1>
                <div class="text-center">
                    <a href="{{ post.get_absolute_url }}">
                        <img src="{% if post.image %}{{ post.image.url }}{% else %}{% static 'img/no-image.jpg' %}{% endif %}" class="post-img" alt="{{ post.title|title }}">
                    </a>
                </div>
                <div class="entry-meta">
                    <span class="post-category"><a
                            href="{{ post.category.get_absolute_url }}">{{ post.category.title|title }}</a></span>
                    <span class="post-date"><a><time class="entry-date">{{ post.created_at }}</time></a></span>
                    <span class="post-author"><a
                            href="{% url 'blog:author' post.author.username %}">{{ post.author.username }}</a></span>
                    <span class="comments-link"><a>{{ post.comment_count }} Comments</a></span>
                </div>
            </header>
            <div class="entry-content clearfix">
                <p>{{ post.content|truncatewords:100 }}</p>
                <div class="read-more cl-effect-14">
                    <a href="{{ post.get_absolute_url }}" class="more-link">Continue reading <span
                            class="meta-nav">→</span></a>
                </div>
            </div>
        </article>
        {% if not forloop.last %}<hr>{% endif %}
        {% empty %}
        <article class="post text-center"><h3>No content</h3></article>
    {% endfor %}
    {% include 'inc/_paginator.html' %}
{% endblock %}

blog_app/blog/templates/blog/navbar.html
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Simple Blog</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="#">About</a>
                </li>
                <li>
                    <a href="#">Login</a>
                </li>
                <li>
                    <a href="#">Sign up</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

blog_app/blog/templates/blog/paginator.html
<ul class="pager">
    <li class="previous">
        <a href="#">Prev</a>
    </li>
    <li class="next">
        <a href="#">Next</a>
    </li>
</ul>